### ISSUE TITLE
連續呼叫 connect, disconnect, reconnect 會發生無法掌控的問題

### ISSUE THREAD

**Issue by momocow** [momocow/node-cq-websocket#5]
需 debouncing 機制, 並且維護一個內部的狀態值

內部狀態總共 6 個值, 分別對應以下事件
- `disabled` (對應事件: 無)
- `init` (對應事件: 無)
- `connecting` (對應事件: `socket.connecting`)
- `connected` (對應事件: `socket.connect`)
- `closing` (對應事件: `socket.closing`)
- `closed` (對應事件: `socket.close`)

### TODO
- [x] 只有處於 `init` 或 `closed` 狀態可以呼叫 connect
- [x] 只有處於 `connected` 可以呼叫 disconnect
- [x] 只有處於 `init`, `connected` 或 `closed` 可以呼叫 reconnect
- [x] 處於 `disabled` 呼叫任何連線方法均沒有效果

**Comment by momocow** [comment]
[連線測試](https://github.com/momocow/node-cq-websocket/tree/master/test/connection)
