### ISSUE TITLE
💥 Public API improvements

### ISSUE THREAD

**Issue by momocow** [momocow/node-cq-websocket#61]
## 🏁 Objective
1. To ~~make the SDK look **cool**~~ encourage the **Functional Programming**.
2. Inspired by [Highland.js](https://highlandjs.org/) and [RxJS](https://rxjs.dev/) when I was surveying for how to build complicated web-like pipelines with NodeJS Stream.

> Web-like pipelines are depicted as the following graph.

> The concept of pipeline is actually a nested structure of Transform stream. Some useful utilities can be found at [htoooth/mississippi2](https://github.com/htoooth/mississippi2).

```
               E
             /
      B - D
   /          \
A               F - G
   \          /
        C
```

## 👷 Role
The position of the SDK is as an **event source** to notify about the CQHTTP events and a **library** to provide convenient methods to call CQHTTP APIs.

The role as an event source can have several ways to deliver events, which can serve for a variety of developer's favor.

## 🛠️ Todo
0. [ ] Performance test and analysis for legacy work.

1. [ ] 🌊 Provide proper support for **Stream API**; with Stream API support, users can gain better integration with popular libraries like [Highland.js](https://highlandjs.org/).

2. [ ] 🔍 Provide proper support for **Observable API**; with Observable API support, users can gain better integration with popular libraries like [RxJS](https://rxjs.dev/).

3. [ ] Improve connection state management. #53 

4. [ ] Introduce **namespace** to provide convenience filters.

5. [ ] Introduce **middleware** API to handle events from CoolQ, leave original Event API to low-level events only.

**Comment by momocow** [comment]
Legacy code base is checked out into branch `v2`. Development will be conducted on branch `dev`.

Development style will have TDD a try, spec files will be written asap.
